### ISSUE TITLE
Update documentation for loading sample data in Python 3.6

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#40]
Hi,
If I try to follow the example here: https://traffic-viz.github.io/airports.html?highlight=airport
```
from traffic.data import airports
from traffic.data.samples import belevingsvlucht
```

Then I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'belevingsvlucht'
```

Any ideas what is wrong? This happens with the latest traffic from github.

**Comment by xoolive** [comment]
My mistake, the documentation is not complete. This import only works on Python >=3.7, see:
https://www.python.org/dev/peps/pep-0562/
https://docs.python.org/3/whatsnew/3.7.html


The following workaround works for Python 3.6:
```python
from traffic.data.samples import featured, get_sample
belevingsvlucht = get_sample(featured, "belevingsvlucht")
```

I will leave the issue open until the documentation is updated.

**Comment by xoolive** [comment]
Actually, it was already [here](https://traffic-viz.github.io/samples.html) 😄  
Adding a link in comment.
